name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read
  packages: write

env:
  GIT_USERNAME: "dolbyio-gh-bot"

jobs:
  Validate-And-Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Validate
        env:
          GIT_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew spotlessCheck check assembleDebug --info
